version: "3.9"

networks:
  api-network:
    driver: bridge

services:
  api-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "onsafety-db"
    ports:
      - "3306:3306"
    networks:
      - api-network
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
